[package]
name = "ab-glyph-bug"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ab_glyph_rasterizer = "0.1.8"
png = "0.17.7"
walkdir = "2.3.3"
